### ISSUE TITLE
Is @secretsantamatcherbot not working now?

### ISSUE THREAD

**Issue by kknishev** [zeroone2numeral2/tg-secret-santa-bot#12]
Could you please clarify bot @secretsantamatcherbot is an active or not?

**Comment by zeroone2numeral2** [comment]
Yes, sorry, it's offline. Unfortunately I had to cut on some expenses and the resources I dedicate to telegram bots are no longer what they used to be :( had to turn some of them down, including the Secret Santa bot

**Comment by kknishev** [comment]
It's not a problem, thanks to the fact that your Santa being on vacation i launched mine )) Thank you for your software and your work. Happy NY!
