### ISSUE TITLE
Join command doesn't work in this case

### ISSUE THREAD

**Issue by MasterCruelty** [zeroone2numeral2/tg-secret-santa-bot#7]
A friend of mine clicked <code>join</code> button after we created a <code>/newsanta</code> but the bot doesn't let him to be added.
I don't know why but it seems it's not working only with him.

I summarize the use case below.
1. he taps join
2. the bot redirect him to the private chat.
3. He taps <code>/start</code>
4. The bot replies with this:

[Forwarded from Secret Santa bot 🤫🎅🏼🎁]
Hello "name"!
I can help you organize a Secret Santa 🤫🎅🏼🎁 in your group chats :)
Just add me to a chat and use /newsanta to start a new Secret Santa.

Source code here 

<b><i>instead of </b></i>

🎄 You joined "name" 's Secret Santa!
Now wait for "name" to start it. You will receive your match here, in this chat

**Comment by zeroone2numeral2** [comment]
Thanks for the report.

To debug the issue, it would be helpful to have at least one of these two information:

- the user ID of the user facing the issue
- the chat ID of the group where the Secret Santa is being organized

I believe the easiest way to obtain these two numbers is to install [kotatogram](https://github.com/kotatogram/kotatogram-desktop/releases) (a Telegram Desktop fork that lets you see user and chat IDs) and open the user profile, and the chat profile. There, you'll find a number which is the chat/user ID

For example:

![image](https://user-images.githubusercontent.com/30071771/143840753-4a2b6573-c12e-4e83-93de-6553c541041e.png)

**Comment by MasterCruelty** [comment]
It seems it worked in the end.
I drop the info anyway maybe you can see more details.

User: 249384467
Group: 1252911537

**Comment by zeroone2numeral2** [comment]
It eventually worked so I will close the issue. The bot now logs the /start command payload to debug other deeplinking issues
